version: "3.8"

services:
  backend:
    build: .
    container_name: Backend-OneLanguage
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5438/proyect_onelanguage
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Johan2509