spring.application.name=Backend-OneLanguage
server.port=${SERVER_PORT:8084}

# --- Database Connection ---
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5438/proyect_onelanguage}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Johan2509}

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Hibernate JPA ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# JWT Configuration
jwt.secret=3dc0db5ab0d89f8b7718efee3c0db5ab0d89f8b7718efee3c0db5ab0d89f8b
jwt.expiration=86400000